namespace JamieHighfield.CredentialProvider.Interop
{
    public enum CREDENTIAL_PROVIDER_GET_SERIALIZATION_RESPONSE
    {
        CPGSR_NO_CREDENTIAL_NOT_FINISHED,
        CPGSR_NO_CREDENTIAL_FINISHED,
        CPGSR_RETURN_CREDENTIAL_FINISHED,
        CPGSR_RETURN_NO_CREDENTIAL_FINISHED,
    }
}